class Task < ApplicationRecord
  belongs_to :project, optional: true
  belongs_to :agent
  has_many :runs, dependent: :destroy
  has_many :volume_mounts, dependent: :destroy

  validates :project_id, presence: true

  after_create :create_volume_mounts

  def run(prompt)
    run = runs.create!(prompt: prompt)
    RunJob.perform_later(run.id)
    run
  end

  def workplace_mount
    @workplace_mount ||= volume_mounts.find_or_create_by!(volume: nil) do |vm|
      # volume_name will be generated by the before_validation callback
    end
  end

  private

  def create_volume_mounts
    agent.volumes.each do |volume|
      volume_mounts.find_or_create_by!(volume: volume)
    end
    workplace_mount # Create workplace mount
  end
end
